name: "Setup Deno"
outbound-endpoints:
  - fqdn: raw.githubusercontent.com
    port: 443
    reason: to fetch code for deno setup
  - fqdn: github.com
    port: 443
    reason: to set up a specific version of deno
harden-runner-link: https://app.next-linux.systems/github/arjundashrath/NextLinux_Tests/actions/runs/1716868818
