name: "Download a Build Artifact"
outbound-endpoints:
  - fqdn: pipelines.actions.githubusercontent.com
    port: 443
    reason: to download artifact
harden-runner-link: https://app.next-linux.systems/github/varunsh-coder/actions-playground/actions/runs/1533688369
