name: "Semgrep Action"
outbound-endpoints:
  - fqdn: semgrep.dev
    port: 443
    reason: to connect with Semgrep App
harden-runner-link: https://app.next-linux.systems/github/h0x0er/kb_setup/actions/runs/1717422313
