name: Knowledge-base Test
on:
  push:
    branches:
      - knowledge-base # to test new KBs

permissions: # added using https://github.com/nextlinux/secure-workflows
  contents: read
concurrency:
  group: ${{ github.workflow }}
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: nextlinux/harden-runner@v2.4.0 # v1
        with:
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            proxy.golang.org:443
            sum.golang.org:443
            storage.googleapis.com:443
            objects.githubusercontent.com:443
            golang.org:443
      - name: Checkout
        uses: actions/checkout@v2 # v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Go
        uses: actions/setup-go@v2.1.3 # v2.1.3
        with:
          go-version: 1.17
      - name: Run coverage
        run: go test ./...  -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic
        env:
          PAT: ${{ secrets.PAT }}
